package Main;

// Para indicar todas las direcciones alrededor de una ficha (por ejemplo para verificar si hay un ganador)
public enum Direccion {
    ATRAS_ARRIBA,
    ATRAS_ABAJO,
    ATRAS_IZQUIERDA,
    ATRAS_DERECHA,
    ATRAS_IZQUIERDA_ARRIBA,
    ATRAS_IZQUIERDA_ABAJO,
    ATRAS_DERECHA_ARRIBA,
    ATRAS_DERECHA_ABAJO,
    CENTRO_ARRIBA,
    CENTRO_ABAJO,
    CENTRO_IZQUIERDA,
    CENTRO_DERECHA,
    CENTRO_IZQUIERDA_ARRIBA,
    CENTRO_IZQUIERDA_ABAJO,
    CENTRO_DERECHA_ARRIBA,
    CENTRO_DERECHA_ABAJO,
    ADELANTE_ARRIBA,
    ADELANTE_ABAJO,
    ADELANTE_IZQUIERDA,
    ADELANTE_DERECHA,
    ADELANTE_IZQUIERDA_ARRIBA,
    ADELANTE_IZQUIERDA_ABAJO,
    ADELANTE_DERECHA_ARRIBA,
    ADELANTE_DERECHA_ABAJO,
}
